### PR TITLE
Bump minJosmVersion for JOSM r17867

### PR DESCRIPTION
**Pull request by tsmock**
This fixes [JOSM #20882](https://josm.openstreetmap.de/ticket/20882)

Note: It looks like the build is failing since I haven't set a `GITHUB_ACCESS_TOKEN` variable.

### CODE REVIEW

**Comment by tsmock** [comment]
This is ready for review with the caveat that the min compile version needs to be updated to tomorrow's nightly.

**Comment by Gubaer** [comment]
Thanks @tsmock! Sorry for the delay. I'm working on it.

**Comment by tsmock** [comment]
No problem -- you really couldn't have merged it yesterday, as I needed to update the compile version to something that could be downloaded. And I consider < 1 week response times to be good for OSS anyway. :)

**Comment by Gubaer** [comment]
Merged and published in [v1.0.7](https://github.com/Gubaer/josm-contourmerge-plugin/releases/tag/v0.1.7)

Thanks a lot!

**Pull request merged**
